=== servicecatalog/oscm/oscm-app-vmware/javares/META-INF/Loadbalancer_schema.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:ess="http://oscm.org/xsd" targetNamespace="http://oscm.org/xsd">
<xs:element name="essvcenter">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="balancer" maxOccurs="unbounded" minOccurs="0">
          <xs:complexType>
            <xs:simpleContent>
              <xs:extension base="xs:string">
				<xs:attribute name="class">
				  <xs:simpleType>
				    <xs:restriction base="xs:string">
					  <xs:enumeration value="org.oscm.app.vmware.business.balancer.EquipartitionHostBalancer"/>
					  <xs:enumeration value="org.oscm.app.vmware.business.balancer.DynamicEquipartitionHostBalancer"/>
					  <xs:enumeration value="org.oscm.app.vmware.business.balancer.SequentialHostBalancer"/>
					  <xs:enumeration value="org.oscm.app.vmware.business.balancer.EquipartitionStorageBalancer"/>
					  <xs:enumeration value="org.oscm.app.vmware.business.balancer.DynamicEquipartitionStorageBalancer"/>
				      <xs:enumeration value="org.oscm.app.vmware.business.balancer.SequentialStorageBalancer"/>
				    </xs:restriction>
				  </xs:simpleType>
				</xs:attribute> 
                <xs:attribute name="cpuWeight">
					<xs:simpleType>
					  <xs:restriction base="xs:float">
					    <xs:minInclusive value="0"/>
					    <xs:maxInclusive value="1"/>
					  </xs:restriction>
					</xs:simpleType>
				</xs:attribute> 
				<xs:attribute name="memoryWeight">
					<xs:simpleType>
					  <xs:restriction base="xs:float">
					    <xs:minInclusive value="0"/>
					    <xs:maxInclusive value="1"/>
					  </xs:restriction>
					</xs:simpleType>
				</xs:attribute> 
				<xs:attribute name="vmWeight">
					<xs:simpleType>
					  <xs:restriction base="xs:float">
					    <xs:minInclusive value="0"/>
					    <xs:maxInclusive value="1"/>
					  </xs:restriction>
					</xs:simpleType>
				</xs:attribute>
				<xs:anyAttribute processContents="skip"/>
              </xs:extension>
            </xs:simpleContent>
          </xs:complexType>
        </xs:element>
        <xs:element name="host" maxOccurs="unbounded" minOccurs="0">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="balancer" maxOccurs="unbounded" minOccurs="0">
                <xs:complexType>
                  <xs:simpleContent>
                    <xs:extension base="xs:string">
					  <xs:attribute name="class">
					    <xs:simpleType>
						  <xs:restriction base="xs:string">
						    <xs:enumeration value="org.oscm.app.vmware.business.balancer.EquipartitionStorageBalancer"/>
							<xs:enumeration value="org.oscm.app.vmware.business.balancer.DynamicEquipartitionStorageBalancer"/>
							<xs:enumeration value="org.oscm.app.vmware.business.balancer.SequentialStorageBalancer"/>
						    </xs:restriction>
						  </xs:simpleType>
						</xs:attribute> 
                      <xs:attribute type="xs:string" name="storage" use="required"/>
                    </xs:extension>
                  </xs:simpleContent>
                </xs:complexType>
              </xs:element>
            </xs:sequence>
            <xs:attribute type="xs:string" name="enabled" use="optional"/>
            <xs:attribute type="xs:string" name="name" use="optional"/>
            <xs:attribute type="xs:string" name="limit" use="optional"/>
          </xs:complexType>
        </xs:element>
        <xs:element name="storage" maxOccurs="unbounded" minOccurs="0">
          <xs:complexType>
            <xs:simpleContent>
              <xs:extension base="xs:string">
                <xs:attribute type="xs:string" name="enabled" use="optional"/>
                <xs:attribute type="xs:string" name="limit" use="optional"/>
                <xs:attribute type="xs:string" name="name" use="required"/>
              </xs:extension>
            </xs:simpleContent>
          </xs:complexType>
        </xs:element>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
</xs:schema>

=== servicecatalog/oscm/oscm-app-vmware/resources/xml/loadbalancer_config.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<!-- Copyright FUJITSU LIMITED 2018-->
<ess:essvcenter xmlns:ess="http://oscm.org/xsd" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://oscm.org/xsd ../../oscm-app-vmware\\resources\\XSD\\Loadbalancer_schema.xsd">
	<balancer class="org.oscm.app.vmware.business.balancer.EquipartitionHostBalancer" cpuWeight="0.5" memoryWeight="1" vmWeight="1"/>
	<host enabled="true" name="estvmwdev1.intern.est.fujitsu.com">
		<balancer class="org.oscm.app.vmware.business.balancer.EquipartitionStorageBalancer" storage="VMdev0,VMdev1"/>
    </host>
	<host enabled="true" name="estvmwdev2.intern.est.fujitsu.com">
		<balancer class="org.oscm.app.vmware.business.balancer.EquipartitionStorageBalancer" storage="VMdev0,VMdev1"/>
    </host>
    <storage enabled="true" limit="85%" name="VMdev0"/>
    <storage enabled="true" limit="85%" name="VMdev1"/>
</ess:essvcenter>
